/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/network/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Посадки маршрутов и остановок по часам даты: кадры тепловой карты */
        get: operations["load"];
        put?: never;
        /** Кадры тепловой карты по сценарию */
        post: operations["loadScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Пересчёт по сценарию
         * @description Ползунки из /api/v1/coefficients и события. Возвращает ряд сценария, базовый ряд и разницу. Одинаковые сценарии берутся из кэша.
         */
        post: operations["scenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Выгрузка прогноза по умолчанию
         * @description level=route|stop|network, ids через запятую (пусто - все объекты уровня). Маршруты по часам за весь горизонт совпадают с сабмитом.
         */
        get: operations["export"];
        put?: never;
        /** Выгрузка прогноза по сценарию */
        post: operations["exportScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Все остановки сети с маршрутами */
        get: operations["stops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Маршруты: число остановок и посадки за горизонт по умолчанию */
        get: operations["routes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{route}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Остановки маршрута по направлениям и доли посадок (оценка) */
        get: operations["routeStops"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Трассы по направлениям и остановки (GeoJSON, OSM и справочник организаторов) */
        get: operations["network"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Паспорт модели: версия, горизонт, качество на лидерборде и бэктесте */
        get: operations["meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Прогноз по умолчанию
         * @description Горизонт day - сутки по часам, month - месяц по дням, year - ноябрь 2025 - октябрь 2026 по месяцам. Без горизонта ряд строится от from до to с шагом granularity.
         */
        get: operations["forecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Внешние факторы: календарь, погода по часам, загруженность дорог, пассажиропоток города, интервалы движения по расписанию, посадки по дням за январь-октябрь 2025, события сети */
        get: operations["factors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coefficients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ползунки: значение по умолчанию, диапазон, шаг и источник */
        get: operations["coefficients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Событие: умножает прогноз маршрута (или всех, если маршрут не задан) в датах и часах */
        EventDto: {
            /**
             * Format: int32
             * @description маршрут; пусто - все маршруты
             * @example 17
             */
            route?: number;
            /** @example 2025-11-22 */
            from?: string;
            /** @example 2025-11-23 */
            to?: string;
            /**
             * @description окно часов, пусто - весь день
             * @example 10-18
             */
            hours?: string;
            /**
             * Format: double
             * @description 0 - перекрытие, 1.2 - рост на 20 %
             * @example 0
             */
            multiplier?: number;
            /** @example Перекрытие на Сущёвском Валу */
            label?: string;
        };
        NetworkLoadRequest: {
            /** @example 2025-11-03 */
            date?: string;
            /** @example 6-23 */
            hours?: string;
            coefficients?: {
                [key: string]: unknown;
            };
            events?: components["schemas"]["EventDto"][];
        };
        NetworkLoadResponse: {
            /** Format: date */
            date?: string;
            hours?: number[];
            timezone?: string;
            scenario?: boolean;
            routes?: components["schemas"]["SeriesDto"][];
            stops?: components["schemas"]["SeriesDto"][];
        };
        SeriesDto: {
            id?: string;
            values?: number[];
        };
        /** @description Что и за какой интервал прогнозировать */
        ForecastQueryDto: {
            /**
             * @description route, stop, segment или network
             * @example route
             */
            level?: string;
            /**
             * @description маршрут для route и segment, id остановки для stop
             * @example 17
             */
            id?: string;
            /**
             * Format: int32
             * @description направление участка, 0 или 1
             */
            direction?: number;
            /** @description первая остановка участка */
            fromStop?: string;
            /** @description последняя остановка участка */
            toStop?: string;
            /**
             * @description начало интервала
             * @example 2025-11-03
             */
            from?: string;
            /**
             * @description конец интервала включительно
             * @example 2025-11-03
             */
            to?: string;
            /**
             * @description окно часов суток
             * @example 7-9
             */
            hours?: string;
            /** @description hour, day или month */
            granularity?: string;
            /** @description day, month или year */
            horizon?: string;
        };
        /** @description Пересчёт прогноза с другими коэффициентами и событиями */
        ScenarioRequest: {
            query?: components["schemas"]["ForecastQueryDto"];
            /**
             * @description ключ ползунка из /api/v1/coefficients -> значение
             * @example {
             *       "level_dec": 1.05
             *     }
             */
            coefficients?: {
                [key: string]: unknown;
            };
            events?: components["schemas"]["EventDto"][];
        };
        ScenarioPointDto: {
            period?: string;
            /** Format: double */
            p50?: number;
            /** Format: double */
            p10?: number;
            /** Format: double */
            p90?: number;
            /** Format: double */
            baseline?: number;
            /** Format: double */
            delta?: number;
            /** Format: double */
            deltaPct?: number;
        };
        ScenarioResponse: {
            target?: components["schemas"]["TargetDto"];
            horizon?: string;
            granularity?: string;
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            hours?: string;
            timezone?: string;
            points?: components["schemas"]["ScenarioPointDto"][];
            total?: components["schemas"]["ScenarioPointDto"];
            coefficients?: {
                [key: string]: unknown;
            };
            events?: components["schemas"]["EventDto"][];
            notes?: string[];
        };
        TargetDto: {
            level?: string;
            id?: string;
            name?: string;
            estimate?: boolean;
        };
        ExportRequest: {
            /**
             * @description csv или xlsx
             * @example xlsx
             */
            format?: string;
            /**
             * @description route, stop или network
             * @example route
             */
            level?: string;
            /** @description пусто - все объекты уровня */
            ids?: string[];
            from?: string;
            to?: string;
            hours?: string;
            granularity?: string;
            horizon?: string;
            coefficients?: {
                [key: string]: unknown;
            };
            events?: components["schemas"]["EventDto"][];
        };
        DataBuffer: unknown;
        StopDto: {
            id?: string;
            name?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lon?: number;
            source?: string;
            routes?: number[];
        };
        RouteDto: {
            /** Format: int32 */
            route?: number;
            /** Format: int32 */
            stops?: number;
            /** Format: double */
            forecastTotal?: number;
            /** Format: double */
            forecastPerDay?: number;
        };
        RouteStopDto: {
            /** Format: int32 */
            direction?: number;
            /** Format: int32 */
            seq?: number;
            stopId?: string;
            name?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lon?: number;
            /** Format: double */
            share?: number;
        };
        MetaResponse: {
            modelVersion?: string;
            gitCommit?: string;
            generatedAt?: string;
            /** Format: date */
            forecastOrigin?: string;
            /** Format: date */
            horizonFrom?: string;
            /** Format: date */
            horizonTo?: string;
            routes?: number[];
            timezone?: string;
            /** Format: double */
            leaderboardWapeScore?: number;
            defaultSubmission?: string;
            quality?: {
                [key: string]: unknown;
            };
            applicability?: string[];
        };
        ForecastResponse: {
            target?: components["schemas"]["TargetDto"];
            horizon?: string;
            granularity?: string;
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            hours?: string;
            timezone?: string;
            unit?: string;
            points?: components["schemas"]["PointDto"][];
            total?: components["schemas"]["PointDto"];
            notes?: string[];
        };
        PointDto: {
            period?: string;
            /** Format: double */
            p50?: number;
            /** Format: double */
            p10?: number;
            /** Format: double */
            p90?: number;
        };
        CoefficientDto: {
            key?: string;
            label?: string;
            group?: string;
            type?: string;
            defaultValue?: unknown;
            min?: unknown;
            max?: unknown;
            /** Format: double */
            step?: number;
            source?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    load: {
        parameters: {
            query?: {
                /** @example 2025-11-03 */
                date?: string;
                /**
                 * @description окно часов
                 * @example 6-23
                 */
                hours?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NetworkLoadResponse"];
                };
            };
        };
    };
    loadScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkLoadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NetworkLoadResponse"];
                };
            };
        };
    };
    scenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScenarioResponse"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: {
                /** @description csv или xlsx */
                format?: string;
                /** @example route */
                level?: string;
                /**
                 * @description id через запятую
                 * @example 17,25
                 */
                ids?: string;
                from?: string;
                to?: string;
                hours?: string;
                granularity?: string;
                horizon?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DataBuffer"][];
                };
            };
        };
    };
    exportScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DataBuffer"][];
                };
            };
        };
    };
    stops: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StopDto"][];
                };
            };
        };
    };
    routes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RouteDto"][];
                };
            };
        };
    };
    routeStops: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RouteStopDto"][];
                };
            };
        };
    };
    network: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DataBuffer"];
                };
            };
        };
    };
    meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    forecast: {
        parameters: {
            query?: {
                /**
                 * @description route, stop, segment или network
                 * @example route
                 */
                level?: string;
                /**
                 * @description маршрут (route, segment) или id остановки (stop)
                 * @example 17
                 */
                id?: string;
                direction?: number;
                fromStop?: string;
                toStop?: string;
                /** @example 2025-11-03 */
                from?: string;
                /** @example 2025-11-03 */
                to?: string;
                /**
                 * @description окно часов
                 * @example 7-9
                 */
                hours?: string;
                /** @description hour, day, month */
                granularity?: string;
                /** @description day, month, year */
                horizon?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ForecastResponse"];
                };
            };
        };
    };
    factors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DataBuffer"];
                };
            };
        };
    };
    coefficients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CoefficientDto"][];
                };
            };
        };
    };
}
