"""Use actual historical probe predictions as L1 observations, not exact totals.

A ceiling probe measures sum min(y,H); treating it as sum y can bias margins.
No new probe files are generated by this script.
"""
import hashlib,json
import numpy as np
import pandas as pd
from s103_recentered_entropy import ROOT,CACHE
from s98_joint_scenarios import OUT,ipf,balanced_round
from s93_entropy_scores import posterior
from s84_block_probes import grid,T
TABLE=ROOT/'docs/analysis/tables/exact_probe_v21'


def observations(g):
    registry=json.loads((ROOT/'forecasts/leaderboard_results.json').read_text())
    for row in json.loads((ROOT/'forecasts/probes_v11/ledger.json').read_text()):
        if row.get('score') is not None and row['score']>0:
            registry.append(dict(file='probes_v11/'+row['file'],sha256=row['sha256'],leaderboard_score=row['score']))
    pool=[];scores=[];seen=set();records=[]
    for r in registry:
        raw=(ROOT/'forecasts'/r['file']).read_bytes();sha=hashlib.sha256(raw).hexdigest()
        assert r['sha256'] in [sha,hashlib.sha256(raw.replace(b'\r\n',b'\n')).hexdigest()]
        if sha in seen:continue
        seen.add(sha)
        frame=g[['route','date','hour']].merge(pd.read_csv(ROOT/'forecasts'/r['file'],sep=';'),on=['route','date','hour'],validate='one_to_one')
        pool.append(frame.prediction.to_numpy());scores.append(r['leaderboard_score']);records.append(r)
    return np.array(pool),np.array(scores),records


def validate():
    TABLE.mkdir(parents=True,exist_ok=True);rows=[]
    for key in ['R06','R08','B']:
        a=np.load(OUT/f'validation_{key}.npz');y=a['y'];total=y.sum()
        cons=[(m.astype(bool),v,str(j)) for j,(m,v) in enumerate(zip(a['A'],a['b']))]
        markov=balanced_round(ipf(np.load(OUT/f'{key}_markov_0.8.npy'),a['A'],a['b']),cons)
        pool=np.r_[a['pool'],markov[None]];scores=np.r_[a['scores'],round(float(1-abs(markov-y).sum()/total),5)]
        champion=pool[scores.argmax()];score0=1-abs(champion-y).sum()/total
        # Historical probes are in-memory simulations, never upload files.
        # Exact likelihood permits arbitrary heights; negative clipped scores
        # cannot recover an L1 measurement and are excluded.
        probes=[];ps=[]
        for mask in a['A'][1:]:
            for height in [2.]:
                # Known route-17 carrier lies outside the measured block.
                routes=np.tile(np.repeat([1,5,7,11,12,17,25,26,28,50],24),len(y)//240)
                carrier=(routes==17)&(mask==0)
                probe=np.zeros_like(champion);probe[carrier]=1.6*champion[carrier]+3
                probe[mask>0]=height*champion[mask>0]+15
                s=round(float(1-abs(probe-y).sum()/total),5)
                if s>0:probes.append(probe);ps.append(s)
        pool=np.r_[pool,np.array(probes)];scores=np.r_[scores,ps]
        # Old aggregate constraints here are truly known (oracle sums), a stronger
        # comparator than potentially clipped real probes; report this difference.
        for center in ['original','champion']:
            anchor=a['original'] if center=='original' else champion
            pred,meta=posterior(anchor,pool,scores,np.ones((1,len(y))),np.array([total]),total,noise_multiplier=a['mult'],distribution='mixture',maxiter=1000)
            for weight in [.5,1.]:
                p=ipf((1-weight)*champion+weight*pred['mean'],np.ones((1,len(y))),np.array([total]))
                score=1-abs(p-y).sum()/total
                rows.append(dict(fold=key,center=center,weight=weight,score=score,gain=score-score0,fit_rmse=meta['score_rmse'],probes=len(probes)))
            print(rows[-2:],flush=True);pd.DataFrame(rows).to_csv(TABLE/'validation_matched.csv',index=False)
    summary=pd.DataFrame(rows).groupby(['center','weight']).gain.agg(['mean','min']);summary['selection']=summary['mean']+.5*summary['min'];summary.to_csv(TABLE/'selection_matched.csv');print(summary,flush=True)


def future_audit():
    TABLE.mkdir(parents=True,exist_ok=True)
    g=grid();pool,scores,records=observations(g)
    multiplier=np.load(ROOT/'forecasts/prior_family_v19/prior_parameters.npz')['multiplier']
    original=pd.read_csv(ROOT/'forecasts/submission_r17_measured_v13.csv',sep=';').prediction.to_numpy(dtype=float)
    champion=pd.read_csv(ROOT/'forecasts/submission_prior_family_v19.csv',sep=';').prediction.to_numpy(dtype=float)
    pred,meta=posterior(original,pool,scores,np.ones((1,len(g))),np.array([T]),T,noise_multiplier=multiplier,distribution='mixture',maxiter=1500)
    np.savez_compressed(CACHE/'exact_probe_future.npz',**pred)
    pd.DataFrame(dict(file=[r['file'] for r in records],observed=scores,fitted=meta['fitted_scores'])).to_csv(TABLE/'future_score_fit.csv',index=False)
    (TABLE/'observations.json').write_text(json.dumps(records,indent=2)+'\n')
    (TABLE/'future_diagnostic.json').write_text(json.dumps(meta,indent=2)+'\n')
    print('FUTURE',meta,flush=True)

if __name__=='__main__':
    import sys
    future_audit() if '--future' in sys.argv else validate()
